
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Копируем go.mod и go.sum
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем приложение
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin/url-shortner ./cmd/app


FROM alpine:latest

WORKDIR /app

# Копируем бинарник из этапа сборки
COPY --from=builder /app/bin/url-shortner .

# Открываем порт
EXPOSE 8080

# Переменная окружения (может быть переопределена)
ENV PORT=8080

# Запускаем приложение
CMD ["./url-shortner"]